version: "3.3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - /tmp/mysql/data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=ingweb
      - MYSQL_DATABASE=maquinas
      - MYSQL_USER=ing-web
      - MYSQL_PASSWORD=ing-web1234
    networks:
      - backend_1
  ing-web:
    build: .
    restart: always
    ports: 
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/maquinas
      - SPRING_DATASOURCE_USERNAME=ing-web
      - SPRING_DATASOURCE_PASSWORD=ing-web1234
    depends_on: 
      - mysql
    links:
      - mysql
    networks:
      - backend_1


networks:
  backend_1: