spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:
    username: 
    password: 
   
 
springdoc:
    api-docs:
        path: /api/open-api
    swagger-ui:
        path: /api/docs
        
       