spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/KXJnJWVLEL
    username: KXJnJWVLEL 
    password: xbOjszIbcC
   
 
springdoc:
    api-docs:
        path: /api/open-api
    swagger-ui:
        path: /api/docs
        
       